defaults:
  - sft_config
  - val_datasets:
    - omr12k_2048
    - omr12k_4096
    - math500
    - competition_math_500
    - gsm8k
    - aime
    - amc
  - _self_

model:
  attn_implementation: flash_attention_2

data:
  train_data_path: data/OMR12k-2048/train.jsonl

training:
  output_dir: ckpt/exp1_sft_omr2048_12k
  batch_size: 16
  gradient_accumulation_steps: 4

evaluation:
  eval_steps: 10
  save_steps: 50
  generation_max_tokens: 4096

logging:
  use_wandb: true
  wandb_project: cs336-assignment5-alignment
  wandb_run_name: exp1_sft_omr2048_12k

# uv run cs336_alignment/train_sft.py --config-name exp1_sft_omr2048_12k